version: '3'
services:
    api:
        build:
            dockerfile: Base.Dockerfile
            context: ../build/package/
        image: ${APP_NAME:-xproject}:base
        command: sh -c "go run *.go"
        volumes:
            - ../:/go/src/github.com/pavlov-tony/xproject
        env_file:
            - ../build/package/dev_config.env
        environment:
            - PROFILE=DEV
        ports:
            - "8080:8080"
        container_name: ${APP_NAME:-xproject}-api
        networks: 
            - default-network
        depends_on: 
            - postgres
    postgres:
        build:
            dockerfile: PG.Dockerfile
            context: ../build/package/
        volumes:
            - xproject-pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=xproject
            - POSTGRES_PASSWORD=xproject
        ports:
            - '5432:5432'
        container_name: ${APP_NAME:-xproject}-postgres
        networks: 
            - default-network

networks:
  default-network:

volumes:
    xproject-pgdata:
        external:
            name: xproject-pgdata
