version: '2.1'
services:
    api:
        build:
            dockerfile: Base.Dockerfile
            context: ../build/package/
        image: ${APP_NAME:-xproject}:base
        command: sh -c "go test -v ./... -tags integration"
        volumes:
            - ../:/go/src/github.com/yemelin/xproject
        env_file:
            - ../build/package/dev_config.env
        environment:
            - PROFILE=TEST
        ports:
            - "8080:8080"
        working_dir: /go/src/github.com/yemelin/xproject
        container_name: ${APP_NAME:-xproject}-api-test
        networks: 
            - default-network
        depends_on: 
            postgres:
                condition: service_healthy
    postgres:
        build:
            dockerfile: PG.Dockerfile
            context: ../build/package/
        volumes:
            - ../scripts/initdb/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
        environment:
            - POSTGRES_USER=xproject
            - POSTGRES_PASSWORD=xproject
        container_name: ${APP_NAME:-xproject}-postgres-test
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U xproject"]
            interval: 0.5s
            retries: 4
        networks: 
            - default-network

networks:
  default-network:
